### ISSUE TITLE
recommendations on how to use pre-release

### ISSUE THREAD

**Issue by petermichaux** [mojombo/semver#114]
The pre-release part of the version is free-form. I think it would be beneficial to recommend, with SHOULD clauses (not MUST clauses), that the following are the ones to use

 -alpha.1
 -alpha.2
 -beta.1
 -beta.2
 -rc.1
 -rc.2

**Comment by maxpolk** [comment]
As a follow-on comment to this closed issue, it looks like there is no special meaning, and the specification defines pre-release versions as `[0-9A-Za-z-]` on purpose.  Examples `0.3.7` and `x.7.z.92` for pre-release are given to prove that no special permutations exist, and `alpha` has no more meaning than `alice` or `x.7.z.92` or anything else.  By definition it's random letters and digits, and the only meaning is that it's pre-release of some kind ("*...unstable and might not satisfy the intended compatibility requirements...*").

Some modern software practices may have weekly pre-release versions for two months, and arbitrarily recommending only **three** "alpha, beta, rc" is inadvisable and inflexible when you require eight or more.  I appreciate that that we aren't bound or forced to use a small set of values that already seems to be waning in popularity.
