### ISSUE TITLE
You should make it clear that you are talking about Package versioning and not API versioning

### ISSUE THREAD

**Issue by jdubray** [mojombo/semver#156]
Tom, 

with all due respect your recommendation is dangerous and will fail people who use it. My understanding is that you translated your development experience in the world of APIs, unfortunately, it does not work that way.

There are at least 3 problems with your recommendation.

The first one is relative to #3. You are recommending what is called an "immutable" versioning strategy. That approach will kill you. I have seen several organizations adopting that approach and it looks like for v1,2 and 3, after a couple of years you have between 15 and 30 "immutable" versions in production and as you can easily imagine as a Service/API provider you are dead

The second one is that none of your recommendation are made at the protocol level, if you ever had implemented your recommendation you would realize that you need two kinds of versions, one that identifies the service/API and the other one that identifies when the client was built (i.e. what version of the service was in effect when the client was built). That's why people use major and minor version.  The bottom line is that the service/API does not care about the client version, it only cares to know which version of the service was in effect when the client was built. 

The third problem is that you make no distinction between forward and backward compatibility. Again, developers tend to dismiss the distinction as it does not really appear in traditional development. If you want to convince yourself of the difference between the two, I would recommend you think about your favorite office suite opening a particular document and how document versions and client versions relate.

I believe your recommendation is more than counterproductive and should be removed altogether until you understand the principles of API versioning. 

Jean-Jacques Dubray
http://www.infoq.com/articles/contract-versioning-comp2

**Comment by jwdonahue** [comment]
Related:
#90 
#314 
#331

**Comment by jwdonahue** [comment]
@jdubray, unless you have any actionable requests to add here, please close this issue at your earliest possible convenience.

**Comment by jwdonahue** [comment]
@jdubray 

I've tried to consolidate all of the "API should be changed X" and similar issues into #468. Please contribute to this discussion on that thread and close this one at your earliest possible convenience.

Thank you.

**Comment by jwdonahue** [comment]
@jdubray, unless you intend to follow [the process outlined in the CONTRIBUTING.md](https://github.com/semver/semver/blob/master/CONTRIBUTING.md) and issue an RFC, or you have further questions, please close this issue at your earliest possible convenience.
