### ISSUE TITLE
Optional addition of a binary version

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [mojombo/semver#162]
The current spec only seems to cover the static/source version of software. There is, however, also the binary version of the software.

I see two use-cases:
- A developer is developing an application, and has some dependency on a library. This library is distributed together with the application. If a new version of the library is released, it can only be included in the next version of the application itself. The application is then recompiled.
- A developer is developing an application, is also has a dependency on the library, but the library is not distributed together with the application. Some package manager on the computer of the end user has to dynamically link the correct package with the application when it is executed. The package of the application is not recompiled in this case.

For the first use-case, only static/source level compatibility is relevant, because the application is recompiled when it is redistributed.

For the second use-case only binary level compatibility is relevant. An application may only be linked to a library if that version is completely compatible with the version it was intended for. Now, one might say the binary version indicator of a library is equivalent to the major indicator of the source level, because that is the only time there are breaking changes. However, this is not always the case. For an example and more information on binary vs source compatibility see:
http://blogs.msdn.com/b/jmstall/archive/2008/03/10/binary-vs-source-compatibility.aspx

I propose a separate indicator for binary compatibility, which consists of only one number. Three numbers are not necessary because a library is either binary compatible or it is not. A versioning might then look something like `x.y.z|b` where `b` is the binary level indicator. Other formats are, of course, also possible.

A binary level indicator is not always relevant (for example in a web-service) so it should be optional. EDIT: In case the binary level indicator is not present, but a package manager must make a decision about using a version based on binary compatibility, the major version indicator may be used instead of the binary version indicator.

**Comment by jwdonahue** [comment]
@LasseBlaauwbroek, this seems to be yet another "what should SemVer versions formally cover?" discussions. Since there as been no action taken on this and no discussion since 2014, unless you intend to submit a PR to semver/semver.org for review, please close this issue.

See also:
#90 
#156
#314 
#331

**Comment by LasseBlaauwbroek** [comment]
This is indeed such a discussion. Does this, in your opinion, make the issue invalid? I do not personally have the time nor the necessary writing experience to actually make a PR. Even if I did, I would not be willing to make such an investment if I had no indication that the maintainers agree, in principle, with my proposal.

However, my lack of time and experience does not necessarily merit this issue to be closed. In my opinion this issue raises a valid concern and contains an actionable proposal that would cater to this concern.

**Comment by jwdonahue** [comment]
@LasseBlaauwbroek, 

Not at all, it's just not actually being discussed anymore, and there's no evidence of actions being taken on it. The issue can be reopened if/when someone has additional input. I am trying to reduce the back-log of opened issues that are not likely to result in any change to the spec.  I am also cross-linking ideas such as this one for further analysis later on. I for one am a champion of replacing the instances of "API" with something else, and expanding the spec a bit, but from what I've seen the past week of reviewing open issues, there's little chance of that happening.

**Comment by LasseBlaauwbroek** [comment]
So if I understand you correctly, you see some merit in this issue but you are still in favour of closing it. Although I agree that it is currently unlikely that action will be taken on this issue, closing it would only make it less likely. I can understand you wanting to create some structure in the open issues. However, closing unresolved issues for the solve purpose of reducing the back-log seems counterproductive and is only a cosmetic solution since nothing is actually getting fixed.

If you really wish to bring some order to the chaos, I suggest you try to categorize the open issues and maybe assign some labels to them (you would have to ask the maintainers of course).

**Comment by jwdonahue** [comment]
@LasseBlaauwbroek 

Well I wish you luck. I don't see this proposal having any chance of success, but I hope eventually the ABI/Binary/Package issues will be addressed.
