### ISSUE TITLE
New logo election

### ISSUE THREAD

**Issue by olivierlacan** [mojombo/semver#171]
@Tieske suggested that in a [Shields](https://github.com/badges/shields/issues/36#issuecomment-23728321) issue and I think it's a very good point.

While we don't use brands for Shields badges (text only) I can point to Dustin Curtis' [Markdown Mark](http://dcurt.is/the-markdown-mark) as a perfect example of a simple brand that made it much easier to succinctly refer to Markdown.

## UPD: Scroll to the [latest messages](https://github.com/semver/semver/issues/171#issuecomment-683603683) to vote for a new logo!

**Comment by jwdonahue** [comment]
@olivierlacan 

This is an interesting idea, but it seems more like something needed in GitHub than in SemVer itself. Am I missing something?  

One idea I've been pondering is exactly how can we express classification data for version strings (version meta). It's not something that SemVer should drive, but maybe something that it would be an early adopter of, once a workable standard was published.  It wouldn't be written into the standard, but the release versions of SemVer would use it to refer to it's own data. This might be as simple as a prefix or postfix tag referencing some kind of human and machine readable schema indicating the policies applied to generate the version number.  It could start with whether it's a marketing, package, hardware/software/human interface, or a relationship expression and include definitions for all of the fields.

**Comment by JimiC** [comment]
My proposal for a logo.

Letters stand for:
`SV`: Semantic Versioning
`M`: Major
`m`: minor
`P`: Patch

Coloring may vary.

![semantic-versioning-logo](https://user-images.githubusercontent.com/1716442/36378549-ed7bcfe4-1583-11e8-9fac-263b52af5615.png)

**Comment by JimiC** [comment]
Alternative versions.

v1
----
![semantic-versioning-logo v2](https://user-images.githubusercontent.com/1716442/36379380-01d1061e-1587-11e8-8e96-b6aebe5ff6bf.png)

v2
----
![semantic-versioning-logo v3](https://user-images.githubusercontent.com/1716442/36379383-05831dc4-1587-11e8-9b1a-e38f5ace1b1e.png)

**Comment by Offirmo** [comment]
A logo would indeed be nice. How about this one?

![semver](https://user-images.githubusercontent.com/603503/55354694-1749de00-5512-11e9-884a-8c4420df69d6.png)


Rationale:
* square logo that seems to be trending in the community https://github.com/voodootikigod/logo.js
* strict colors inspired by the current website and hinting at seriousness
* big font to be readable at low resolution
* simple, to the point

The elements were hand-placed to optimize volume harmony, i.e. semver is intentionally not perfectly centered.

Public domain, feel free to iterate as will.

**Comment by grv87** [comment]
If a project uses semver logo, it would be better if the link on the logo leads to their description of public API (or what they consider breaking changes).

I agree with @jwdonahue that the logo is not the part of semver per se.
But if we can make logo valuable (not just nice image) then the logo could make its way to the FAQ.

**Comment by Offirmo** [comment]
Slightly improved version: 
![semver](https://user-images.githubusercontent.com/603503/55364262-bc24e500-552b-11e9-9750-e5d309dcd01c.png)

**Comment by alexandrtovmach** [comment]
Hello guys!
I hope you're still interested in making logo for SemVer. Here is open Figma document, and anyone can share his idea:
https://www.figma.com/file/NyAORxkcDNGHIqgYn0brnW/SemVer-Logo?node-id=0%3A1

**Comment by alexandrtovmach** [comment]
Plan:

1. We're collecting logo variants until **July 31, 2020**. Please share your ideas :gem: 
2. Feel free to invite :incoming_envelope: your friends :handshake: in this competition 
3. In **August 2020** we will start voting for the new SemVer logo by the whole community
4. My hope is to have new logo at **September 1, 2020**, but as you know ― "no estimates in open source", so it's just approximate date

P.S. Figma preferred just because it's possible to edit designs in browser, but it's not requirement

**Comment by maxhaz** [comment]
I'd like to propose something slightly different.
<br>
<img width="450" alt="logo-sv" src="https://user-images.githubusercontent.com/8924271/87124332-91dfdc80-c2c3-11ea-97da-1e47751160d9.png">
<br>

(the color variations follow the theme of the current site and the one being updated /semver/semver.org#256).
The idea here is to allow the use of the logo by APIs and software that follow semantic versioning guidelines. 

See the examples below.
<br>
<img width="400" alt="logo-sv" src="https://user-images.githubusercontent.com/8924271/87126310-f0f32080-c2c6-11ea-8df9-1cf9c5de42f1.png">

**Comment by JimiC** [comment]
@maxhaz I really really like the logo. To the point and usable in GUI's too. Nice. :+1:

**Comment by alexandrtovmach** [comment]
@maxhaz Would you add your logo ideas to [Figma](https://www.figma.com/file/NyAORxkcDNGHIqgYn0brnW/SemVer-Logo)?

**Comment by maxhaz** [comment]
@alexandrtovmach Sure. Let me see how to do that.

**Comment by maxhaz** [comment]
@JimiC Than you! @alexandrtovmach I just added the logo to Figma.

**Comment by maxhaz** [comment]
@JimiC Thank you!
@alexandrtovmach I just added the logo to Figma. I can edit upon request. Glad to help.

**Comment by Pablo-No** [comment]
> 3. In August 2020 we will start voting for the new SemVer logo by the whole community
How can we vote?

**Comment by alexandrtovmach** [comment]
@Pablo-No 
I'm busy now, will provide more details soon in August

**Comment by JimiC** [comment]
@alexandrtovmach Ehmmm it **IS** August.

**Comment by alexandrtovmach** [comment]
> Ehmmm it IS August.
I know, thanks for a reminder, but 31 Aug, it's still August :smile: 
Sorry for the delay I was busy with other stuff, and haven't enough time :shrug:

**Comment by alexandrtovmach** [comment]
Thanks everyone for proposed designs, and now we'll start the election!

## How to vote?
1. Open [Figma](https://www.figma.com/file/NyAORxkcDNGHIqgYn0brnW/SemVer-Logo)
2. Check all available logo designs
3. Comment in this thread with designer name (only once)

## Results?
You can vote until **September 30, 2020**. Then all votes will be count, and results will be announced here. Later we need to agreed new logo with core maintainers, and if everything okay we'll add logo to the website, GitHub org etc.

Hope it's clear and open, feel free to ask if you have any questions

**Comment by JimiC** [comment]
My vote to `maxhaz`.

**Comment by Tieske** [comment]
`maxhaz` as well

**Comment by KeithBush** [comment]
Another one for @maxhaz

**Comment by Pablo-No** [comment]
I vote to maxhaz.

**Comment by DNA** [comment]
@maxhaz! 👍🏻

**Comment by klehelley** [comment]
I vote for maxhaz too. :grin:

**Comment by earnal** [comment]
I vote @maxhaz !

**Comment by Offirmo** [comment]
@maxhaz your logo is very nice but I find it a bit generic. I wish we would see something "semver-ish" in the logo. Maybe dot separators? The "tick" ✔️ design also makes it look like a Continuous Integration badge IMO.

Just my 2 cents, the logo is great and can always be improved in the future!

**Comment by maxhaz** [comment]
@Offirmo great comments, thank you. I hold them back for possible edit.
If you have CI badges in mind, that would be awesome.

I would say that the simple, "tick"-ish design is no coincidence :smiley:

**Comment by Pablo-No** [comment]
First of all congratulations @maxhaz for winning, I think everyone has voted you.
The election has ended, how is the process of changing logo?
