### ISSUE TITLE
specify prefixed by 'v' or not

### ISSUE THREAD

**Issue by greggman** [mojombo/semver#204]
I've only recently learned for semver and it was in relation to creating an npm package. It directed me to http://semver.org/ which I read. Semver.org only refers to digits an an optional prefix is in **0.1.2-foo**

So I went off and added some git tags in the form of **d.d.d** as in 

```
git tag -a 0.0.1 -m 0.0.1
```

Then later I found out about `npm version` which will auto increment and auto tag version numbers. But, it's tags are prefixed with a **v** as in **v0.0.2**

http://semver.org mentions nothing about prefixing semvers. So is 'v' a valid prefix on a semver? How about other letters? Can I put **f0.1.2** as a valid semver?  This seems like it should be specified. Even at the top of http://semver.org/ there are **'v'** prefixes. Is capital **'V'** valid? What about unicode full width **'ｖ'**?

Yes I know I'm being a little silly here. My point is only it seems like the it should be specified explicitly which prefixes are allowed and if they are required or optional. My impression is only prefixing by lowercase ascii **'v'** is allowed and that it is optional but since it's not specified I have no idea. I'm just guessing.

**Comment by laguiz** [comment]
Reading this thread tell me to *not* use `v` anywhere to avoid confusion. Then everywhere (doc, tag, tooling, etc.) we don't talk about `v` and life is easy :) 

In the other hand if I want to make my tagging clear then I prefix my *non version* tags with something else.

**Comment by i5okie** [comment]
old post i kno.. I haven't dug around at all. 
But reading above that SemVer removed the 'v' prefix at 2.0.0..
Has any of you thought about the fact that "version" and therefore the shorthand 'v' is not the same in every language?

**Comment by beck** [comment]
@i5okie the FAQ addresses v-prefixing well enough. No reason to stir-up old bikesheds.

**Comment by i5okie** [comment]
I'm not here to stir-up anything lol.
Sorry which FAQ are you referring to?
on semver.org?

**Comment by i5okie** [comment]
indeed. comment deleted :)

**Comment by montanaflynn** [comment]
@mojombo and @beck I didn't find anything in the FAQ about prefixing. 

With `vgo` coming out and requiring the prefix I think people like myself might end up here.

**Comment by beck** [comment]
@montanaflynn it is the last question in the FAQ:
https://github.com/semver/semver/blob/master/semver.md#is-v123-a-semantic-version

@mojombo (or maybe @Haacked?) any chance at publishing a release to https://semver.org/ ?

**Comment by anks333** [comment]
Check this: https://semver.org/#is-v123-a-semantic-version

**Comment by janArb** [comment]
Hey, I don't understand the point in tagging with prefix 'v' if that is not officially specified for semantic versioning. This is due increasing automation, e.g. with Ansible Galaxy. There GIT repos are directly referenced and a dependency file looks like

```
roles:
  - src: https://github.com/pbalu-code/ansible-postgresql.git
    scm: git
    name: pbalucode.postgresql
    version: v2.3.0
```

The version string is directly used to checkout a tag, i.e. if the tag is created with prefix 'v', the version string is now not confirming semantic versioning anymore. 

As this seems to be out in the wild I would also prefer to raise this and only this optional prefix to the standard and call it semantic version again to avoid confusion. Otherwise it's pointless to say we use semantic versioning if tags are created this way.

**Comment by beck** [comment]
@janArb this is an old bikeshed that is probably best left alone. I was curious how Ansible Galaxy does versioning, looking at [version.py](https://github.com/ansible/galaxy/blob/d70755f23bc3901e9aa03e2e47cc7795803819bc/galaxy/common/version.py#L72) - it seems like the v-prefixing is for grouping version tags, and `get_version_name()` is hardcoded to return `"Doin' it Right"` so it looks like there is room for improvement 😁

**Comment by ljharb** [comment]
@janArb because tags can be for anything, the `v` helps mark which tags are versions and which aren't. It's a useful and widespread convention.

**Comment by theherk** [comment]
@@janArb, are there situations where a tag will match a semver specified version string and not be a version? I never run into a situation where it isn't completely superfluous. Cutting the end off the ham, it seems.

**Comment by ljharb** [comment]
@theherk it would be wildly inefficient to validate every tag for semver instead of filtering by tags that start with "v" first.

**Comment by theherk** [comment]
@ljharb I'm not suggesting there are no situations where the prefix is useful, just that I haven't run into them. Wildly inefficient I suppose would matter if you have very high tags counts, but here is the critical part of my position.

I don't believe any git host should prohibit the use of a "v" prefix or any other tag format. What I'm saying is the prefix doesn't belong as a part of the version string specification. If you want all your tags to be `this-is-a-version-x.y.z` great, but that should be `this-is-a-version-{semver-spec-compliant-tag}`.

**Comment by haacked** [comment]
I agree with @theherk. This discussion has come up before where folks wanted to add a [version range spec to Semver](https://github.com/semver/semver/issues/205).

But it's really the other way around. SemVer is focused specifically on the version number and what incrementing those version numbers communicate about the changes in a new release of software.

It's perfectly valid to propose new specs that build on semver. You could have a Semantic Version Range spec. You could have a a Semantic Version Tag spec. I think it's fine to propose them and see if folks are interested in rallying around them.

I do think there would be some value in a common approach to tagging versions in git. If I am grabbing a tag from Git, it'd be nice to know if the version represents a semver version or not. Of course, so many people use the `v{version}` syntax already, it'd be hard to know if they _intendend_ that to be a semantic version or not. This leads me to think for your git tag, you might want a prefix not commonly used to indicate a semantic version such as `sv{semver-compliant-version}`. But that's a digression. 😄 

Until then, I think it's valid to set a standard for *your* git repositories to tag new versions with `v{semver-compliant-version}` and try to convince others to do so. The `v` doesn't need to be part of the semver spec which is only concerned. with the version number part and not what goes around it.

**Comment by ljharb** [comment]
There's an open PR for ranges: #584, and that makes sense to add imo, but I agree the `v` shouldn't be in the semver spec, although it _should_ be in git tags.

**Comment by ljharb** [comment]
That also applies to the terms "versioning" or "semantic" or "git" or "tag" or "spec" or "major" or "minor" or "patch" etc. I'm not sure that's relevant here.
