### ISSUE TITLE
What if I inadvertently alter the public API in a way that is not compliant with the version number change (i.e. the code incorrectly introduces a major breaking change in a patch release)

### ISSUE THREAD

**Issue by euoia** [mojombo/semver#214]
In the interest of being as clear as possible, referring to the following sentence:

> What if I inadvertently alter the public API in a way that is not compliant with the version number change (i.e. the code incorrectly introduces a major breaking change in a patch release)

Consider rewording to use e.g. (for example) instead of i.e. (that is). Or change the sentence to read:

> What if I inadvertently alter the public API in a way that is not compliant with the version number change (i.e. the code incorrectly introduces a major breaking change in a minor release or a patch release)

**Comment by Timoses** [comment]
I kind of stumbled across this as well.
> What do I do if I accidentally release a backwards incompatible change as a minor version?

Why would I in this case release a new minor version (as stated in the answer)? I would find it more intuitive to release a patch to "fix" the minor version release.

As for the answer to:
> What if I inadvertently alter the public API [...]

A major release with the breaking changes included + a patch release for the broken minor release would sound consistent.

So let's say the history is as follows:
1.0.0 - all good
1.1.0 - oops, released breaking change to API
1.1.1 - fixed the minor version to not break the API
2.0.0 - moved the breaking changes from 1.1.0 into new major release

What do you think?

**Comment by jwdonahue** [comment]
@Timoses wrote:

> So let's say the history is as follows:
1.0.0 - all good
1.1.0 - oops, released breaking change to API
1.1.1 - fixed the minor version to not break the API
2.0.0 - moved the breaking changes from 1.1.0 into new major release

> What do you think?

That seems like a perfectly acceptable solution.

**Comment by jwdonahue** [comment]
@euoia, unless you intend to issue a PR, or have further questions, please close this issue at your earliest possible convenience.
