### ISSUE TITLE
SemVer Spec - Override Extension 

### ISSUE THREAD

**Issue by christian-weiss** [mojombo/semver#219]
If your project (1.0.0) depends on a FooPackage (v 1.2.3) which itself depends on a BarPackage (v 2.5.1) and you may identify a bug in BarPackage. You normally start a fork of BarPackage to fix it and send a pull-request to the maintainer of BarPackage. If you can not wait till the maintainer of the BarPackage integrates it you need to fork FooPackage to update the dependency from BarPackage to ForkOfBarPackage and your project dependencies from FooPackage to ForkOfFooPackage.

Imagine the amount of changed if the dependency chain is longer than that. And after integration you need to update dependency back to the initial definition.
From my point of view a good dependency management software (composer, etc.) should give you an option to force overriding of dependency definition at each level in the dependency chain (without forking the full dependency chain) . I think is is not a direct issue to semver itself. But as discussed earlyer (see other issues, e.g. #17) there is need to solve that issue. 

If we provide a "override extension" spec, we can avoid confusion (here and elsewhere). This would enable use to focus on semantic issues instead of hacking semver to fit to some special cases, that can be solved elsewhere best. When promoting it is a valid job for a dependency manager and if we provide a spec that has the chance to introduce a standard way of declaring that override rules accross all dependency management tools - it can lead to an more focues discussion an the semver spec itself.

The override spec MAY include a behavior spec e.g. to warn if a sub project changes the dependency to another project which may makes our override rule obsolete. In such a case i would ask a human to update / review dependency definition and override rules.

**Comment by jwdonahue** [comment]
@christian-weiss, unless you have questions or intend to issue a PR against this issue, please close it.  It is quite old and unlikely to spur any changes in the spec an the issue currently delineated.
