### ISSUE TITLE
What the difference between semver 1 and 2 ?

### ISSUE THREAD

**Issue by ghost** [mojombo/semver#231]
What the difference between semver 1 and 2 ?

Where is semver 1 scheme like https://github.com/mojombo/semver/blob/master/semver.md and https://github.com/mojombo/semver/blob/master/semver.svg for semver 2?

**Comment by anarcat** [comment]
it's kind of hilarious that semver.org doesn't document those changes while the document itself is pretty strict about documenting those changes itself... :p

to answer the actual question here, it seems most of the changes are:

* addition of the `Summary` section on top
* some clarifications and small fixes
* leading zeros are not accepted
* minor version numbers MUST be incremented if API is marked as deprecated
* the SemVerTag header is removed and the content is clarified
* precedence rules have been added
* build metadata (`+something`) has been added
* some FAQs were added

I suggest something like that be added to the FAQ.

**Comment by EddieGarmon** [comment]
> it's kind of hilarious that semver.org doesn't document those changes while the document itself is pretty strict about documenting those changes itself... :p

SemVer is about documenting the API, not the deltas between the releases.

**Comment by jeremyfrench** [comment]
Perhaps being pedantic here, but is semVer 2.0.0 breaking backwards compatibility? Why is it 2.0.0 not 1.1.0 ?

**Comment by FichteFoll** [comment]
It is, specifically because of

> leading zeros are not accepted

Probably also

> minor version numbers MUST be incremented if API is marked as deprecated

**Comment by jwdonahue** [comment]
The addition of build metadata is also a breaking change from SemVer 1.0.0 because there were/are no specified means to extend the string without updating the standard itself. In other words, SemVer is not extensible.  Also, build metadata added the plus symbol to the spec, which is known to break some implementations that implement SemVer.  Essentially, any string which has embedded in it, what would otherwise be a legal SemVer string if standing alone, is not a SemVer compliant string.

**Comment by jwdonahue** [comment]
@ggrnd0, unless you have any further questions, please close this issue at your earliest possible convenience.

**Comment by FichteFoll** [comment]
What you are talking about is forwards compatibility. The addition of the metadata section adds a new feature but it is backwards compatibility because any 1.0.0 version without a metadata section (and without violating any of the breaking changes I quoted) is still valid in 2.0.0.

**Comment by anarcat** [comment]
> @ggrnd0, unless you have any further questions, please close this issue at your earliest possible convenience.

Would the authors here welcome pull requests that would integrate the above documentation (https://github.com/semver/semver/issues/231#issuecomment-104478395) in the source somehow? shouldn't there be a CHANGELOG that would summarize major changes in the releases?

or could the release tags include those detailed changes?

thanks!

**Comment by jwdonahue** [comment]
@FichteFoll, a non-breaking change to the spec would not break existing parsers.  When metadata was added, it broke existing parsers.  That change alone was sufficient to bump from 1.0.0 to 2.0.0. 

@ggrnd0, you are always welcome to submit PR's.  How welcome that might be will be depend on the details.  Are proposing adding a change log with retro-active entries?  You could always add a  page to the wiki that documents the aspects you can identify that are different.  Then others can come along and refine it as needed.

**Comment by jwdonahue** [comment]
@ggrnd0, in any case, this issue should either be closed or pending a PR.  The wiki page won't require the PR process.  We can refine it and maybe eventually add a log file to the site?  It's up to you.  I don't have the bandwidth to complete that task and you seem to be the only person with the motivation at this point.

**Comment by WalkerCodeRanger** [comment]
> * leading zeros are not accepted

It should be noted that this is not just in major, minor, and patch. It also applies to the pre-release version number. In the v1 spec, "denoted by appending an arbitrary string immediately following the patch version and a dash. The string MUST be comprised of only alphanumerics plus dash [0-9A-Za-z-]." In the v2 spec, "denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes."

The way I read that, it also means that previously "1.2.3-" was a valid version number with an empty pre-release version, but is no longer valid.
