### ISSUE TITLE
Header links to other languages broken

### ISSUE THREAD

**Issue by eLobato** [mojombo/semver#240]
On ```semver.org```, when you click on a language on the header, it should show all other language options.

However, when you choose Korean, Portuguese won't show up. Similarly when you choose Arabic, Japanese will not show up either. I couldn't find a way to fix this on a PR as this is just the English doc.

**Comment by FichteFoll** [comment]
Try this: https://github.com/mojombo/semver.org

**Comment by eLobato** [comment]
Oh dumb me, closing this in favor of https://github.com/mojombo/semver.org/pull/110 and https://github.com/mojombo/semver.org/pull/109
