### ISSUE TITLE
Incorrect Example 10

### ISSUE THREAD

**Issue by idmean** [mojombo/semver#249]
Point 10 of the specification says (emphasis added):

> Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise ***only ASCII alphanumerics and hyphen [0-9A-Za-z-]***. Identifiers MUST NOT be empty. 

Then this example follows:

     1.0.0-beta+exp.sha.5114f85

However the identifier contains periods which are not included in `[0-9A-Za-z-]` nor are they alphanumerics or hyphens.

So is this example incorrect?

**Comment by crazedsanity** [comment]
The given example is correct, as it refers explicitely to the identifiers, which are *separated* by the dots.  So `exp` is valid, `sha` is valid, and `5114f85` is valid as individual identifers; the full metadata is then `exp.sha.5114f85`.  Hopefully that makes sense.
