### ISSUE TITLE
Definitions of versions should include zeroes

### ISSUE THREAD

**Issue by vdtoorn** [mojombo/semver#26]
in item 7. 8. and 9:

Patch version Z (x.y.Z | **x > 0**) MUST be incremented if only backwards compatible bug fixes are introduced. A bug fix is defined as an internal change that fixes incorrect behavior.

Minor version Y (x.Y.z | **x > 0**) MUST be incremented if new, backwards compatible functionality is introduced to the public API. It MUST be incremented if any public API functionality is marked as deprecated. It MAY be incremented if substantial new functionality or improvements are introduced within the private code. It MAY include patch level changes. Patch version MUST be reset to 0 when minor version is incremented.

Major version X (X.y.z | **X > 0**) MUST be incremented if any backwards incompatible changes are introduced to the public API. It MAY include minor and patch level changes. Patch and minor version MUST be reset to 0 when major version is incremented.

the conditions x>0 look out of place, shouldn't that be x>=0, y>=0 and z>=0 at their respective descriptors?

**Comment by arthurliraprof4-boop** [comment]
https://github.com/semver/semver/issues/26
