### ISSUE TITLE
Non-code changes between releases

### ISSUE THREAD

**Issue by Maikuolan** [mojombo/semver#261]
Hi,

For a particular project of mine, I'm not currently using semver, but what I'm currently using is adequately close enough to semver that I feel that it should be possible to migrate over to semver from what I'm currently using if I was to plan it correctly, and I'm thinking about doing that.

Quick question.

For a project of a nature that may potentially contain changes between individual releases that don't have anything to do with code (such as, for example, changes to documentation, configuration defaults or periferal files that the code uses, but which in and of themselves, strictly speaking, aren't code), how would you go about incrementing your version numbers?

Say, for example, Project X is versioned as 1.2.3 at current release, and then a month later, it's re-released with some modified documentation (such as i18n/i10n README translations, for example) or some other modified internal files that aren't code and don't contain code (such as signature files, as could be the case for anti-virus programs, for example). Would this re-release be considered a "patch", and would it therefore be versioned as 1.2.4? Could I version it as something like 1.2.3-r1 (where "r" == release number)? Does semver encourage a different approach, or is there such an approach recommended by semver at all? Or would I be better to simply use my own discretion (and would I be compliant with semver recommendations if I did)?

Thanks. :-)

Kind Regards,
Caleb M / Maikuolan.

**Comment by FichteFoll** [comment]
Increase patch.

`1.2.3-r1` is a pre-release and the exact opposite of what you want.

**Comment by Maikuolan** [comment]
Cheers FichteFoll; I appreciate the help. :-)
