### ISSUE TITLE
List of libraries that conform to the semver specification.

### ISSUE THREAD

**Issue by michaelainsworth** [mojombo/semver#262]
A list of libraries that conform to the semver specification would be helpful, along with the languages that those libraries are written in.

**Comment by zafarkhaja** [comment]
I think the spec is not quite the right place to have a list of implementations but the website is. I've opened an issue about this some time ago mojombo/semver.org#57.

**Comment by zafarkhaja** [comment]
If by a "list of libraries that conform to the SemVer specification" you mean a list of implementations, I don't think the spec is quite the right place to have it but the website is. I've opened an issue about this some time ago mojombo/semver.org#57. On the other hand, if by that you mean libraries that use SemVer for versioning it's going to be a huge list...

**Comment by Haacked** [comment]
Agreed, this shouldn't be in the spec. It should be on the website.
