### ISSUE TITLE
Are these valid numbers?

### ISSUE THREAD

**Issue by BartG95** [mojombo/semver#266]
Are these valid version numbers:
1.0.0-0 (not a leading zero, but just a zero as pre-release version identifier)
1.0.0+some.build.metadata-beta (pre-release version identifier and build metadata swapped)

I understand these versions are rare, but according the standard they are valid. (if read literally).I have to write a regex, so this need to be clarified.

**Comment by FichteFoll** [comment]
`1.0.0-0` is valid, the pre-release indentifier would be interpreted as non-numeric cause lexicographical comparison with a different version.
`1.0.0+some.build.metadata-bet` is valid, `-bet` is part of the last `medatata-bet` identifier, which in turn is part of the build metadata.

**Comment by DavidFichtmueller** [comment]
I agree, both are valid. If you need a RegEx to check, you can use this one: #232 . I hope this helps.

**Comment by BartG95** [comment]
Thanks! I already made an RegEx. According to that RegEx both are valid, I just wanted to make sure it is correct.

For completeness, here's my RegEx:
(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(((0|[1-9]\d*)|[1-9A-Za-z-][0-9A-Za-z-]*)\.)*((0|[1-9]\d*)|[1-9A-Za-z-][0-9A-Za-z-]*))?(\+(([0-9A-Za-z-]+)\.)*([0-9A-Za-z-]+))?

**Comment by DavidFichtmueller** [comment]
Hey BartG95,
I compared your RegEx against mine and found one difference, where I think yours is not confirming to the specs. In section 9 (pre -release version):
> Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. 

The way I understand this, is that only pure numerical identifiers must not have a leading zero, but identifiers that are a mixture between numbers and letters can have a leading zero. So according to the specification ```1.42.0-rc.0-bugs-remaining``` is a valid semver number, but it will not be (completely) captured by your RegEx. 
This is a minor thing, but I noticed it and wanted to let you know.
Cheers
  David

**Comment by BartG95** [comment]
Thanks. I should have looked to this before: https://github.com/mojombo/semver/blob/master/semver.svg
I've update my RegEx to this:
`(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:(?:\d*[A-Za-z-][0-9A-Za-z-]*|(?:0|[1-9]\d*))\.)*(?:\d*[A-Za-z-][0-9A-Za-z-]*|(?:0|[1-9]\d*))))?(?:\+((?:(?:[0-9A-Za-z-]+)\.)*[0-9A-Za-z-]+))?` (http://regexr.com/3bm59)

I also included non-capturing groups, which make it is easier to parse a version.

**Comment by DavidFichtmueller** [comment]
Looks good. Nice use of non-capturing groups. And just in case you don't already know this classic, here is the XKCD about Regular Expressions: http://www.xkcd.com/208/ . Cheers.
