### ISSUE TITLE
Translation to Czech Language

### ISSUE THREAD

**Issue by jakubkrizka** [mojombo/semver#267]
Hi, 
After I find this project I must translate this to my natural language, so there is first version of translate to Czech language: https://goo.gl/h8126m  

@mojombo please help me how can I public this. Thank you

**Comment by FichteFoll** [comment]
https://github.com/mojombo/semver.org

**Comment by taringamberini** [comment]
Hi @jakubkrizka,

I've translated semver into Italian. You should:

1. go to https://github.com/mojombo/semver.org
2. fork the project to your repositories work space by clicking on <kbd>Fork</kbd> Key
3. clone your forked repository on your local pc by running `git clone https://github.com/jakubkrizka/semver.org.git`
4. create a branch for your langage by running `git branch cz_translation`
5. move to that branch by running `git checkout cz_translation`
6. write your translation into `/lang/cz/index.md`
7. add link to your translation updating files into `/_layouts`
8. ask some people who speak your language to review your translation
9. update your translation with reviewers comments
10. create a pull request into `mojombo/semver.org gh-pages` from your `jakubkrizka/semver.org cz_translation`

Hi,
Tarin

**Comment by jakubkrizka** [comment]
Hi @taringamberini 
thank you for help, pull request is ready here: https://github.com/mojombo/semver.org/pull/125

**Comment by jakubkrizka** [comment]
Hi @taringamberini 
is there any problem with translate or pull request?

**Comment by taringamberini** [comment]
Hi @jakubkrizka I don't know, but it should help to give a proof of the correctness of the translation to a non Czech person (point 8 of the list above) who, most likely, will do the merge.

So ask to some of your friends, colleagues, or somone in your local User Groups, to review your translation. In the [Italian translation](http://www.taringamberini.com/en/blog/news/translation/semantic-versioning-2-dot-0-dot-0-tradotto-in-italiano-en/) process you can see [what reviewers have pointed me out](https://github.com/mojombo/semver.org/pull/71).

Reviewers have preferred to [write comments on line diff](https://github.com/taringamberini/semver.org/commit/bb5545ebc96edb6d856c6dedd5c303c32a042485) insted of interact by git directly on source code.

Feel free to find the "collaboration way" which works better for your reviewers.

Hold on and let me know if you have any problem.

Hi,
Tarin

**Comment by FichteFoll** [comment]
The added file lists two correctors, so I assume this already went through some QA passes: https://github.com/mojombo/semver.org/pull/125/files#diff-2f728cf67420f4f4c507ccfe1cd7320dR127

**Comment by taringamberini** [comment]
Yeah, @FichteFoll said it right.

> The added file lists two correctors, so I assume this already went through some QA passes: 
> https://github.com/mojombo/semver.org/pull/125/files#diff-2f728cf67420f4f4c507ccfe1cd7320dR127

I guess @Haacked is going to consider merging this translation as soon as he finds the time. I suppose that if there was something wrong he would tell @jakubkrizka what to do.

I'll refer the pull request in order to trigger an additional advice to merge this translation.

Be patient please.

pull: #125

**Comment by Haacked** [comment]
It's done!

Pro tip, when you create a commit that fixes an issue, add the phrase "Fixes #267" and when that commit is merged, it'll close issue 267.

I will close this issue as the PR has been merged. Thanks for the contribution!
