### ISSUE TITLE
Complete RegExp to verify version numbers

### ISSUE THREAD

**Issue by rugk** [mojombo/semver#279]
Can we possibly have a full regular expression which can be used to formally verify version numbers according to the spec?
Possibly publish them at https://regex101.com/, because there you can later change (and versionize :wink:) it.

This would also allow RegExp pros to just look at this RegExp and get the main ideas how to use semantic verison numbers.

**Comment by rugk** [comment]
This would also prevent such questions: https://github.com/mojombo/semver/issues/271
Because you can easily check it by yourself. :)

**Comment by DavidFichtmueller** [comment]
Take a look at #232 or https://github.com/mojombo/semver/issues/266#issuecomment-135765386 (this one is better). I hope this helps. 
I think this should be part of the specification as well.

**Comment by rugk** [comment]
I also saw https://github.com/mojombo/semver/issues/32 and https://github.com/mojombo/semver.org/issues/59 which have some ideas there.

So I still leave this issue open for adding this to the spec and which would allow keeping the RegExp updated as I found many outdated RegExp in the issues you and I linked to.

**Comment by FichteFoll** [comment]
Note that because of ambiguity in #181 we are currently unable to construct an exact regular expression, although the *unpublished* BNF suggests a solution.

**Comment by rugk** [comment]
As far as I understand [here](https://github.com/mojombo/semver.org/issues/59#issuecomment-57841224) is a RegExp which respects the loading zeros convention.
So do you mean this with BNF or what else?

**Comment by FichteFoll** [comment]
No, in the initial post of #181 it is explained that the spec would be ambiguous whether digits-only identifiers with leading zeros make a valid semantic version. I just came to the conclusion that it's in fact not ambiguous, so you can ignore my comment.

**Comment by Haacked** [comment]
Closing this in lieu of mojombo/semver.org#59
