### ISSUE TITLE
Pre-release and build meta examples contain invalid characters

### ISSUE THREAD

**Issue by clphillips** [mojombo/semver#291]
The spec (version 2.0.0) states that:

>  Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]

Which applies to both **pre-release** (section 9) and **build meta** (section 10). **However**, the examples given include:

> 1.0.0-alpha.1, 1.0.0-0.3.7 ... 1.0.0-beta+exp.sha.5114f85

These clearly violate the rule as they contain full stops (.), which are not alphanumerics or hyphens (e.g. they fall outside [0-9A-Za-z-]).

**Comment by FichteFoll** [comment]
Start reading the two sections at the beginning.

**Comment by clphillips** [comment]
> MAY be denoted by appending a [hyphen|plus sign] and a series of **dot separated identifiers** immediately following the patch version

I swear it wasn't there before. ^_^
