### ISSUE TITLE
[Request] A Chinese translation of the semver v2.0.0 with better typesetting

### ISSUE THREAD

**Issue by plusmancn** [mojombo/semver#294]
The semver is useful for fresh programmer, but the Chinese version from [semver.org](http://semver.org/lang/zh-CN/) was not friendly for humans to read, so i want to modify the Chinese version for better typesetting, and give some explanatory notes to the translation.    
How can i contribute to it?

**Comment by Haacked** [comment]
Sounds good to me!

Submit a PR to https://github.com/mojombo/semver.org and perhaps ping some of the folks who contributed to the original translation to review your changes. For obvious reasons, I'm not the right person to review such translation changes.
