### ISSUE TITLE
Support HTTPS

### ISSUE THREAD

**Issue by bhubbard** [mojombo/semver#302]
http://semver.org should default to HTTPS. This can easily be accomplished with a service like CloudFlare.

**Comment by martinsuchan** [comment]
...or with a free domain certificate from [Let's Encrypt](https://letsencrypt.org/).

**Comment by dragon788** [comment]
Definitely should either do CloudFlare or Let's Encrypt to get HTTPS, was really sad when I was going to link somebody to https://semver.org and got a cert warning.

**Comment by dragon788** [comment]
This should be closed like #186 and any further votes/comments made over at  https://github.com/mojombo/semver.org/issues/86 .

**Comment by Haacked** [comment]
Agreed.
