### ISSUE TITLE
Svg is not readable in github

### ISSUE THREAD

**Issue by danielgomezrico** [mojombo/semver#305]
This is just a visual thing, I had to download the project and see them locally to be able to read the diagram.

Will be cool to have it in a way that people can see it directly in github.

Maybe vertical and with bigger text?

**Comment by simonmysun** [comment]
It's actually a [syntax diagram](https://en.wikipedia.org/wiki/Syntax_diagram) which goes horizontally from left to right. 

The render size of previewing is decided by Github and its width leads to this result. 

I recommend providing a usable and better experience viewer on the 'semver.org' website. (But I didn't find where to contribute)

**Comment by Haacked** [comment]
> I recommend providing a usable and better experience viewer on the 'semver.org' website. (But I didn't find where to contribute)

You can contribute to https://github.com/mojombo/semver.org for the website.
