### ISSUE TITLE
Please allow omitting trailing .0, or document why not

### ISSUE THREAD

**Issue by joshtriplett** [mojombo/semver#308]
I've often seen the question raised about why semver requires a three-component version number, MAJOR.MINOR.PATCH, even if PATCH is 0.  I would suggest one of two things: either document that the version number may omit the trailing .0 if PATCH is 0, or add an entry to the FAQ at the end explaining why not.

**Comment by FichteFoll** [comment]
>A normal version number MUST take the form X.Y.Z
 - [spec 2.](http://semver.org/#spec-item-2)

That's pretty clear to me. People not used to reading specifications will always have problems reading them.

**Comment by joshtriplett** [comment]
I didn't suggest that the specification needs an update to state *that* this isn't allowed; the current spec very clearly disallows it.  I'm suggesting that either the spec should allow this, or it should document the *rationale* for not allowing this.

**Comment by Haacked** [comment]
The rationale is documented in the spec, but not directly.

> These rules are based on but not necessarily limited to pre-existing widespread common practices in use in both closed and open-source software.

Keep in mind that SemVer describes the specification for libraries and packages. It does not dictate how you _market_ your product. So your product is free to call itself "MyWidget 2.0" even if the library version is `2.0.0` or even `2.0.5`.

Another reason for the current rule is to keep things as simple as possible for implementers. Allowing `2.0` and `2.0.0` to be equivalent adds unnecessary complexity. And then why not just `2`?

**Comment by joshtriplett** [comment]
@Haacked "Keeping implementations simple" seems like a completely reasonable reason.  Would you consider adding the explanation you just posted (especially the second half) as a FAQ answer?

**Comment by Haacked** [comment]
> "Keeping implementations simple" seems like a completely reasonable reason. Would you consider adding the explanation you just posted (especially the second half) as a FAQ answer?

Honestly, this is the first time this question has come up as far as I can tell. And it doesn't seem like one that comes up often. If it comes up frequently, I'll reconsider. :smile:
