### ISSUE TITLE
Prefix Info

### ISSUE THREAD

**Issue by johnrs** [mojombo/semver#326]
I often see SemVar strings prefixed by a program or module name.  Something like:  "MyProg-v1.2.3".

I was wondering if this was currently allowed by the spec, in which case what delimiter character should be used?  If not, would it be worth allowing for?

**Comment by Haacked** [comment]
No, SemVer only covers the version. What that string denotes is typically a package/library/program name and version. So the SemVer part is `1.2.3` and only covers that part.
