### ISSUE TITLE
Please be careful with Hillary's data

### ISSUE THREAD

**Issue by BubbaNicholson** [mojombo/semver#334]
It's nice to have all the coders sharing databases, but you really need a fortress mentality.  Place unsanctioned actors into a morphing labyrinth which it will take infinity to master.  
Your adversaries can drug innocent, really good-looking people, even people you know, to betray you. AND THEY WILL.  THEY WILL DRUG YOU!  
I hope to God Almighty that the opening photograph of chumps with flags up and down is fake and that none of those people work on real Hillary or Democratic code.  It would be a lot better if the flaggers were all trained FBI agents wired with cameras 24/7 and were not new to enflurane and it's tricks.  Perhaps if the flaggers were all working on what they THOUGHT was code, too, I'd feel one heck of a lot better, too.  I mean, come on, nobody's that stupid.  Are you?  Don't answer. 
The drug is enflurane.  Discovered by our very own CIA, it was used briefly as a general anesthetic (obviously breathing a lot of it).  It is a clear liquid with a chemical smell that effervesces slowly at room temperature.  One sniff get you to amnesia.  Two sniffs and you're off to the races.  You'll do anything you're told, from taking off knickers to murder to framing (Teddy, Pat Kennedy and Wilbur Mills all with exactly the same M.O.?) to sabotaging your own code perfectly to do exactly the wrong thing at exactly when they want it.  The drug looks rather like vodka and can be carried in a vodka bottle.  It causes amnesia and hypnosis.  It's what the Plumbers gang used to drug the assassins to attack Gabby Giffords, JFK, RFK, MLK, George Wallace, shoot at Bush twice, and wound Ronald Reagan, as well as frame Mills & the Kennedy family.  The Iranians use it to pick off Afghan troops to assassinate our people in Afghanistan.  Republicans use it to rape hundreds of women.  Remember all the copies of "Catcher in the Rye" at crime scenes?  Or how there were geographic centers of pretty girls/cheerleaders with crazy tics?  Tells.  That's how you brag to your pals about banging girls or killing political enemies.  "Oh Mary!--You guys watch this--Mary!"  "Do I know you?"  "Key word--look at her on all fours snorting like a pig!  OK, that's enough.  Second Key word."  
When a policeman opens an enflurane bottle marked as ethanol to check it:  "You see?  That's not the stuff you're looking for!  I can go about my business.  Move along!"  Those famous lines/scene in Star Wars actually came from George W. Bush telling me about how he would get me out of an open container violation if we were caught with his open bottle of enflurane in my little beetle in 1971!  He was awful (he drug-raped seventh graders, hundreds of them), but drugging Gorby and Mandela won us the Cold War.
Look, just don't be chumps.  Be careful, for crying out loud.  The world is full of real evil.  Russians, Republicans, even our own people could be enflurane drugged.  Keep things close to your chest.  I'm hoping and praying that that is exactly what you're doing.

**Comment by MidLifeXis** [comment]
:-1: :bomb: this thread.

**Comment by oleksmarkh** [comment]
omg, please close this spamming attempt :)
