### ISSUE TITLE
Language error in Italian translation

### ISSUE THREAD

**Issue by csparpa** [mojombo/semver#346]
On the Italian version of the website (http://semver.org/lang/it/) I read:

 > Se vi piacerebbe lasciare un commento, per favore aprite una segnalazione su GitHub.

I think in *proper* Italian you should write:

> Se vi __piacesse__ lasciare un commento, per favore aprite una segnalazione su GitHub.

Anyway, I think a reprashing is needed here as it sounds a bit weird...

**Comment by csparpa** [comment]
@mezzato I think you could help here

**Comment by FichteFoll** [comment]
https://github.com/mojombo/semver.org

**Comment by csparpa** [comment]
Closing, as this is tracked by this [PR](https://github.com/mojombo/semver.org/pull/163)
