### ISSUE TITLE
Use HTTPS for semver.org

### ISSUE THREAD

**Issue by mbrodala** [mojombo/semver#351]
Please consider switching semver.org to HTTPS.

**Comment by frog23** [comment]
This is the wrong repository for this kind of issue. This repository deals with the standard itself, the repository for the website semver.org is [mojombo/semver.org](https://github.com/mojombo/semver.org) and there they already have an issue for the https support: mojombo/semver.org#86

**Comment by mbrodala** [comment]
You're right, thanks for the heads up.

**Comment by nainumsunti** [comment]
Mmm
